[package]
name = "disku"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.29"
crossterm = "0.28"
jwalk = "0.8"
libc = "0.2"

[target.'cfg(windows)'.dependencies]
ntfs-reader = "0.4"

[target.'cfg(windows)'.build-dependencies]
winresource = "0.1"
