[package]
name = "disku-tui"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "disku"
path = "src/main.rs"

[dependencies]
disku-core = { path = "../disku-core" }
ratatui = "0.29"
crossterm = "0.28"

[target.'cfg(windows)'.build-dependencies]
winresource = "0.1"
